import { StyleSheet } from 'react-native';
import { horizontalScale, moderateScale, verticalScale } from './Metrics';

export default style = StyleSheet.create({
    author: {
        color: '#ffffff',
        flex: 1,
        fontSize: 17,
        margin: 10,
        textAlign: 'center',
    },
    button: {
        alignItems: 'center',
        backgroundColor: '#2D3250',
        borderColor: '#000000',
        borderBottomLeftRadius: 20,
        borderWidth: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        marginLeft: horizontalScale(35),
        marginRight: horizontalScale(60),
        marginTop: verticalScale(40),
        marginBottom: verticalScale(30),
        padding: moderateScale(8),
        width: horizontalScale(300),

    },
    button2: {
        alignItems: 'center',
        backgroundColor: '#2D3250',
        borderColor: '#000000',
        borderBottomLeftRadius: 20,
        borderWidth: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        marginLeft: horizontalScale(35),
        marginRight: horizontalScale(60),
        marginTop: verticalScale(40),
        marginBottom: verticalScale(20),
        padding: moderateScale(8),
        width: horizontalScale(300),
    },
    buttonText: {
        color: '#ffffff',
        fontSize: 20,
        fontSize: moderateScale(18),
    },
    bonuspointsInfo: {
        marginTop: 20,
    },
    container: {
        backgroundColor: '#fff',
        flex: 1,
        height: verticalScale(70),
        width: horizontalScale(380),
    },

    dataRow: {
        backgroundColor: '#FEECE2',
        marginTop: verticalScale(5),
        marginBottom: verticalScale(10),
        width: horizontalScale(370),
    },
    dataCellNum: {
        flex: 0,
    },
    dataCellName: {
        flex: 1,
    },
    dataCell: {
        flex: 2,
    },
    footer: {
        backgroundColor: '#2D3250',
        flexDirection: 'row',
        marginTop: 30,
        height: verticalScale(50),
        marginTop: verticalScale(10),
    },
    flex: {
        flexDirection: 'row',
    },
    gameboard: {
        alignItems: 'center',
        backgroundColor: '#fff',
        justifyContent: 'center',
    },
    gameinfo: {
        backgroundColor: '#fff',
        fontSize: 20,
        justifyContent: 'center',
        marginTop: 10,
        textAlign: 'center',
    },
    header: {
        backgroundColor: '#FFBE98',
        flexDirection: 'row',
        marginBottom: 15,
        height: verticalScale(40),
        fontSize: moderateScale(90),
    },
    header2: {
        flexDirection: 'row',
        fontSize: 20,
        marginBottom: 10,
        marginTop: 15,
        textAlign: 'center',
        height: verticalScale(50),
        fontSize: moderateScale(20),
    },
    header3: {
        backgroundColor: '#2D3250',
        flexDirection: 'row',
        marginBottom: 20,
        height: verticalScale(60),
        fontSize: moderateScale(10),
    },
    icon: {
        textAlign: 'center',
    },
    pointNum:{
        fontSize: 20,
        marginLeft: 8,
    },
    row: {
        marginTop: 20,
        padding: 10,
    },
    tabStyle: {
        alignContent: 'center',
        alignItems: 'center',
    },
    text: {
        fontSize: 22,
        margin: 8,
        marginTop: 20,
        marginBottom: 10,
        color: '#000000',
        textAlign: 'center',
        marginLeft: horizontalScale(7),
        marginRight: horizontalScale(12),
        padding: horizontalScale(5),
        fontSize: moderateScale(20),
    },
    text2: {
        fontSize: 20,
        marginBottom: 25,
        marginTop: 5,
        margin: 8,
        textAlign: 'center',
        color: '#000000',
        marginTop: verticalScale(10),
        fontSize: moderateScale(20),
    },
    text3: {
        fontSize: 20,
        marginBottom: 10,
        color: '#000000',
        margin: 8,
        textAlign: 'center',
    },
    text4: {
        fontSize: 20,
        margin: 15,
        marginBottom: 10,
        marginTop: 45,
        textAlign: 'center',
        marginTop: verticalScale(20),
        fontSize: moderateScale(20),
    },
    text5: {
        fontSize: 20,
        textAlign: 'center',
        marginTop: verticalScale(22),
        fontSize: moderateScale(21),
    },
    text6: {
        fontSize: 20,
        marginBottom: 10,
        marginTop: 10,
        margin: 8,
        textAlign: 'center',
        color: '#000000',
        marginTop: verticalScale(20),
        fontSize: moderateScale(19),
    },
    textHome: {
        fontSize: 16,
        margin: 15,
        marginBottom: 0,
        textAlign: 'center',
        color: '#000000',
    },
    textTotal: {
        fontSize: 20,
        marginBottom: 0,
        marginTop: 5,
        margin: 8,
        textAlign: 'center',
        color: '#000000',
    },
    textinput: {
        backgroundColor: '#FEECE2',
        borderBottomLeftRadius: 20,
        borderTopRightRadius: 20,
        fontSize: 20,
        padding: 10,
        marginLeft: horizontalScale(20),
        marginRight: horizontalScale(20),
    },
    title: {
        color: '#ffffff',
        flex: 1,
        fontSize: 23,
        margin: 10,
        textAlign: 'center',
        marginTop: verticalScale(10),
        marginBottom: verticalScale(10),
        marginLeft: horizontalScale(6),
        fontSize: moderateScale(20),
    },
    viewRule: {
        backgroundColor: '#FEECE2',
        paddingTop: 5,
        paddingBottom: 20,
        marginLeft: 20,
        marginRight: 20,
        borderBottomLeftRadius: 20,
    },
    viewInfo: {
        backgroundColor: '#FEECE2',
        marginTop: verticalScale(5),
        marginBottom: verticalScale(10),
        width: horizontalScale(375),
    },
});